### ISSUE TITLE
Mod Organizer Tool: Not displaying Name / Version / Author

### ISSUE THREAD

**Issue by SphereII** [Turbero/7DTD-Mods-Desktop#3]
When loading my steam folder, which contains a collection of my Mods, it does not populate the Name, Version, or Author. They do have a ModInfo.xml though.

Attached is an example of one of the Modlets.

[SphereII UMA Tweaks.zip](https://github.com/Turbero/7DTD-Mods-Desktop/files/4161941/SphereII.UMA.Tweaks.zip)

**Comment by Turbero** [comment]
Your ModInfo.xml file contains an invisible byte order mark (BOM). It seems when I read the xml file it fails because of this (I forgot to print out exceptions in the log for the xml parser)

I've read several workarounds for this. I'll come up with one to be compatible with the BOM char. But meanwhile, if you recreate the file without the BOM file (you can check with Notepad++ whether you have it or not as I did) it should work.

**Comment by Turbero** [comment]
Fixed. Created **v1.0.0.4**.

Let me know if you can see now: https://7dtdmodsdesktop.com/download.php

**Comment by SphereII** [comment]
That works better, thank you.

The ModInfo.xml is auto-generated from the mod.xml, which is what the DMT build tool uses. It's important to catch the BOM entries, as they are surprisingly comon.
